// SPDX-License-Identifier: GPL-3.0-only
// Chromium creates/signs CRX3; private key material never enters this repository.
import {generateKeyPairSync, createPublicKey, createHash} from 'node:crypto';
import {access, cp, mkdir, mkdtemp, readFile, rm, writeFile, stat} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {dirname, join, resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
const args = process.argv.slice(2);
const option = name => { const index = args.indexOf(name); return index < 0 ? undefined : args[index + 1]; };
const binary = option('--browser'), keyPath = option('--key');
if (!binary || !keyPath) throw new Error('Usage: node package-crx.mjs --browser CHROMIUM --key PRIVATE_KEY [--initialize-key]');
const root = fileURLToPath(new URL('.', import.meta.url));
const key = resolve(keyPath);
if (key.startsWith(root)) throw new Error('Keep the private signing key outside this repository.');
if (args.includes('--initialize-key')) {
  try { await access(key); throw new Error('Refusing to overwrite an existing signing key.'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  await mkdir(dirname(key), {recursive: true, mode: 0o700});
  const pair = generateKeyPairSync('rsa', {modulusLength: 3072, privateKeyEncoding: {type: 'pkcs8', format: 'pem'}, publicKeyEncoding: {type: 'spki', format: 'pem'}});
  await writeFile(key, pair.privateKey, {mode: 0o600, flag: 'wx'});
}
if ((await stat(key)).mode & 0o077) throw new Error('Signing key permissions must be private (chmod 600).');
const publicDER = createPublicKey(await readFile(key)).export({type: 'spki', format: 'der'});
const publicKey = publicDER.toString('base64');
const id = createHash('sha256').update(publicDER).digest('hex').slice(0, 32).replace(/[0-9a-f]/g, c => String.fromCharCode(97 + parseInt(c, 16)));
const manifestPath = join(root, 'extension/manifest.json');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
if (manifest.key && manifest.key !== publicKey) throw new Error('Signing key does not match the extension identity.');
manifest.key = publicKey;
await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
const temp = await mkdtemp(join(tmpdir(), 'still-crx-'));
try {
  await cp(join(root, 'extension'), join(temp, 'extension'), {recursive: true, filter: path => !path.split('/').includes('_metadata')});
  const result = spawnSync(binary, ['--headless=new', '--no-message-box', '--user-data-dir=' + join(temp, 'profile'), '--pack-extension=' + join(temp, 'extension'), '--pack-extension-key=' + key], {encoding: 'utf8', timeout: 60000});
  if (result.error || result.status !== 0) throw new Error(result.error?.message || result.stderr || 'Chromium packaging failed.');
  const crx = await readFile(join(temp, 'extension.crx'));
  if (crx.subarray(0, 4).toString() !== 'Cr24' || crx.readUInt32LE(4) !== 3) throw new Error('Expected a signed CRX3 archive.');
  const output = join(root, 'package'); await mkdir(output, {recursive: true});
  await writeFile(join(output, 'still-blocking.crx'), crx);
  await writeFile(join(output, 'identity.h'), `// Generated by Still package-crx.mjs. Public identity only.\n#ifndef CHROME_BROWSER_EXTENSIONS_STILL_BLOCKING_IDENTITY_H_\n#define CHROME_BROWSER_EXTENSIONS_STILL_BLOCKING_IDENTITY_H_\nnamespace still_blocking {\ninline constexpr char kExtensionId[] = "${id}";\ninline constexpr char kVersion[] = "${manifest.version}";\n}  // namespace still_blocking\n#endif\n`);
  await writeFile(join(output, 'metadata.json'), JSON.stringify({id, version: manifest.version, bytes: crx.length, sha256: createHash('sha256').update(crx).digest('hex'), publicKey}, null, 2) + '\n');
  console.log(`Signed ${id} version ${manifest.version}: ${crx.length} bytes.`);
} finally { await rm(temp, {recursive: true, force: true}); }
