// Generated by Still package-crx.mjs. Public identity only.
#ifndef CHROME_BROWSER_EXTENSIONS_STILL_BLOCKING_IDENTITY_H_
#define CHROME_BROWSER_EXTENSIONS_STILL_BLOCKING_IDENTITY_H_
namespace still_blocking {
inline constexpr char kExtensionId[] = "acckjhcnbonppllgbaknbacfekcoeikp";
inline constexpr char kVersion[] = "0.1.0";
}  // namespace still_blocking
#endif
